### ISSUE TITLE
question about single modality

### ISSUE THREAD

**Issue by Jiawei0o0** [YaoZhang93/MAML#2]
Hi, thanks for sharing your great work. I am confused about how the model works when the modality is one.  The data is going through two different u-net branches or sharing the same one. According to your code, I think it may be the first one.  But in this manner, it can't be thoughts of as mutual learning, cause it generates the same response. 
I am looking forward to your reply.  Thanks a lot.

**Comment by YaoZhang93** [comment]
Hi, 

thanks for your interests.

You are right about the framework. Each modality will go through a corresponding modality-specific model (a U-Net in our case) for feature extraction. I am not sure if I get it right of what you mean by "it generates the same response" so I will try to explain it under my understanding. "Mutual Learning" here is enabled by a joint loss that make the modality-specific models exchange information with each other DURING TRAINING PROCEDURE. When only 1 modality is available, the corresponding modality-specific model is used for inference. You may see more details in the paper. Hope it helps.

Best,
Yao

**Comment by Jiawei0o0** [comment]
Hi, thanks for your reply! 
" It generates the same response " means the model got the same modality-specific information. 
When only one modality is available, the model here is more like to exchange information with two u-net models(no sharing parameters). In this manner, it works more like ensemble learning. Am I right? 
And for the inference phase,  Is the final segmentation output is the average of all the models？

**Comment by YaoZhang93** [comment]
Yes, It is an ensemble learning of a set of modality-specific models. We propose a Modality-aware module that performs an adaptive fusion of all modality-specific models.

**Comment by Jiawei0o0** [comment]
Hi, sorry to bother you. I have a question about the data label process. It seems two-way for me.
first one :
        ed_volume = (seg_volume == 2) # peritumoral edema ED
        net_volume = (seg_volume == 1) # enhancing tumor core NET
        et_volume = (seg_volume == 4) # enhancing tumor ET
second one :
  wt_volume = seg_volume > 0  
  tc_volume = np.logical_or(seg_volume == 4, seg_volume == 1)
 et_volume = (seg_volume == 4)

I think you may use the first one. Does it make difference in the performance?

**Comment by YaoZhang93** [comment]
Do you mean the label for evaluation?
You may follow the [paper](https://ieeexplore.ieee.org/abstract/document/6975210/) of BRATS benchmark.
![image](https://user-images.githubusercontent.com/58619665/144559758-10b9063e-6b32-4682-965f-318b97955942.png)

**Comment by YaoZhang93** [comment]
I might get your point now. The first one is much more common but I also think the second one will work. As for the second one, the network will pay more attention to label 4 as it is a part of all volumes (wt, tc, and et). It is not easy to say which is better but it is worthy to try.

**Comment by Jiawei0o0** [comment]
Thanks for your reply!
I would like to make a fair comparison. In my experiments, it led to different results. So I'm curious which is more commonly used. Thanks again!
